apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: my-ns
  labels:
    app: node-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-2
  template:
    metadata:
      labels:
        app: node-app-2
    spec:
      containers:
      - name: node-app-2
        image: {app:master}
        args: ["start",  "app-second"] 
        ports:
        - containerPort: 8080