kind: Service
apiVersion: v1
metadata:
  name: app-one-service
  namespace: my-ns
spec:
  selector:
    app: node-app-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
  protocol: TCP
  port: 9229
  targetPort: ws